### ISSUE TITLE
Add a tool repairing tool

### ISSUE THREAD

**Issue by ExcaliburZero** [ExcaliburZero/moretechnictools#1]
Create a technic tool that can be charged, and then used to restore the wear of a selected tool. This would give players the ability to use tools more without having to return to use a Tool Workshop. The portability of the tool would provide a portable alternative to the Tool Workshop.

This too would need to have an expensive crafting recipe, long charge time, and low number of uses per full charge in order to prevent abuse of the tool.

In terms of coding the tool, take a look at PilzAdam's Throwing mod (WTFPL) to see how the bow and arrow setup works in order to apply that to resetting the wear of a tool in a specific inventory slot.

The tool could either fully restore a tool to its max wear amount, or it could instead just increase the current wear of the tool. The latter would likely be the better idea.

**Comment by HybridDog** [comment]
You could add a mk1, mk2 and mk3 tool repairing tool.
The mk3 version could automatically repair your wielded tool every 10 seconds if you configure it to do this.

**Comment by ExcaliburZero** [comment]
Different versions of the tool sounds like an interesting idea. Though I think I have to be a bit careful with the effectiveness of the tool, because if it is not properly ballanced then it could be abused a bit.

I already have most of the coding done for the tool.

**Comment by ExcaliburZero** [comment]
I have finished coding the Tool Repairer, and I have added it to the repository.
